name: "Balto - TypeScript"
description: "Run TypeScript checks on your repo"
runs:
  using: composite
  steps:
    - uses: planningcenter/balto-typescript/yarn@composite
    - uses: planningcenter/balto-typescript/action@composite
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        conclusionLevel: ${{inputs.conclusion_level}}
branding:
  icon: life-buoy
  color: orange
inputs:
  conclusionLevel:
    description: 'Which check run conclusion type to use when annotations are created ("neutral" or "failure" are most common)'
    required: false
    default: "neutral"
outputs:
  issuesCount:
    description: "Number of eslint violations found"
