name: "Balto - TypeScript Check"
description: "Run TypeScript checks on your repo"
runs:
  using: node20
  main: dist/index.js
branding:
  icon: life-buoy
  color: orange
inputs:
  conclusionLevel:
    description: 'Which check run conclusion type to use when annotations are created ("neutral" or "failure" are most common)'
    required: false
    default: "neutral"
outputs:
  issuesCount:
    description: "Number of TypeScript violations found"
